using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;
public class GUIPanel : MonoBehaviour
{
    [SerializeField]
    TextMeshProUGUI display;
    [SerializeField]
    VectorField field;

    void Update(){
        int identifier = (int)(field.fieldType);

        switch(identifier)
        {
            case 0:
                display.SetText($"This is an Outwards field. All of the vectors are pointing outwards");
                break;
            case 1:
                display.SetText($"This is an Swirl field. All of the vectors are swirling");
                break;
            case 2:
                display.SetText($"This is the Magnetic field generated by the magnet. The field can be computed with a formula. Can you guess what it is?");
                break;
            case 3:
                display.SetText($"This is the DeltaB/DeltaT field generated by the magnet.");
                break;
            case 4:
                display.SetText($"This is the Integrand field. Nothing to see here.");
                break;
            case 5:
                display.SetText($"This is the Electric field. It is computed using the Faraday-Maxwell formula for Electric field.");
                break;   
        }
        
        
    }
}