using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;
public class GUIPanel : MonoBehaviour
{
    [SerializeField]
    TextMeshProUGUI display;
    [SerializeField]
    VectorField field;

    private float time;
        
    

    void Update(){
        //time = Time.time;
        //Debug.Log(time);
        if (time <= 5.0f){
            display.SetText("Welcome. In 5 seconds we will see the magnetic field generated by the magnet.");
        }
        // else if (time > 5.0f && time < 20f){
        //     field.fieldType = VectorField.FieldType.Coulomb;
        //     string fieldName = "" + field.fieldType;
        //     display.SetText($"This is the Magnetic field. In 15 seconds we will see the electric field generated by the magnet.");
        // }
        // else if (time < 30f){
        //     field.fieldType = VectorField.FieldType.CalculateElectricField;
        //     string fieldName = "" + field.fieldType;
        //     display.SetText($"This is the Electric field");
        // }
        // else{
        //     display.SetText("That's it. Feel free to roam around.");
        // }

    }
}